export const SPORTS_OPTIONS = [
  { key: "NFL" as const, label: "NFL", icon: "🏈" },
  { key: "NBA" as const, label: "NBA", icon: "🏀" },
  { key: "MLB" as const, label: "MLB", icon: "⚾" },
  { key: "NHL" as const, label: "NHL", icon: "🏒" },
];

// Available symbols from your subscriptions.json
export const AVAILABLE_SYMBOLS = [
  "AAPL",
  "MSFT",
  "NVDA",
  "GOOGL",
  "AMZN",
  "META",
  "TSLA",
  "BRK.B",
  "TSM",
  "AVGO",
  "LLY",
  "WMT",
  "JPM",
  "V",
  "UNH",
  "XOM",
  "ORCL",
  "MA",
  "COST",
  "PG",
  "HD",
  "NFLX",
  "JNJ",
  "BAC",
  "NVO",
  "CRM",
  "ABBV",
  "CVX",
  "SAP",
  "TMUS",
  "KO",
  "ASML",
  "MRK",
  "WFC",
  "ACN",
  "CSCO",
  "TM",
  "BX",
  "AMD",
  "ADBE",
  "PEP",
  "LIN",
  "MS",
  "NOW",
  "MCD",
  "DIS",
  "NVS",
  "PM",
  "AXP",
  "BINANCE:BTCUSDT",
  "ETH",
];

// Filter out crypto symbols for stock presets
export const STOCK_SYMBOLS = AVAILABLE_SYMBOLS.filter(
  (symbol) => !symbol.includes("BINANCE:") && !["ETH", "BTC"].includes(symbol)
);

// Crypto symbols available
export const CRYPTO_SYMBOLS = AVAILABLE_SYMBOLS.filter(
  (symbol) => symbol.includes("BINANCE:") || ["ETH", "BTC"].includes(symbol)
);

export const STOCK_PRESETS = [
  {
    key: "sp500",
    label: "S&P 500",
    symbols: [
      "AAPL",
      "MSFT",
      "NVDA",
      "GOOGL",
      "AMZN",
      "META",
      "TSLA",
      "BRK.B",
      "TSM",
      "AVGO",
      "LLY",
      "WMT",
      "JPM",
      "V",
      "UNH",
      "XOM",
      "ORCL",
      "MA",
      "COST",
      "PG",
      "HD",
      "NFLX",
      "JNJ",
      "BAC",
      "CRM",
      "ABBV",
      "CVX",
      "TMUS",
      "KO",
      "MRK",
      "WFC",
      "ACN",
      "CSCO",
      "AMD",
      "ADBE",
      "PEP",
      "LIN",
      "MS",
      "NOW",
      "MCD",
      "DIS",
      "PM",
      "AXP",
    ],
  },
  {
    key: "nasdaq",
    label: "NASDAQ",
    symbols: [
      "AAPL",
      "MSFT",
      "NVDA",
      "GOOGL",
      "AMZN",
      "META",
      "TSLA",
      "AVGO",
      "COST",
      "NFLX",
      "AMD",
      "ADBE",
      "CRM",
      "CSCO",
      "PEP",
    ],
  },
  {
    key: "dow",
    label: "Dow Jones",
    symbols: [
      "AAPL",
      "MSFT",
      "AMZN",
      "UNH",
      "HD",
      "JPM",
      "V",
      "PG",
      "JNJ",
      "WMT",
      "MA",
      "CVX",
      "MRK",
      "KO",
      "CSCO",
      "MCD",
      "DIS",
      "AXP",
    ],
  },
];

export const CRYPTO_PRESETS = [
  {
    key: "top10",
    label: "Top 10",
    symbols: ["BINANCE:BTCUSDT", "ETH"], // Only available crypto symbols
  },
  {
    key: "defi",
    label: "DeFi Coins",
    symbols: ["ETH"], // Only ETH available from your subscriptions
  },
  {
    key: "meme",
    label: "Meme Coins",
    symbols: [], // No meme coins in your current subscriptions
  },
];

// Updated STOCK_OPTIONS to only include symbols from subscriptions.json
export const STOCK_OPTIONS = [
  { key: "AAPL", label: "Apple Inc.", enabled: true },
  { key: "MSFT", label: "Microsoft Corporation", enabled: true },
  { key: "GOOGL", label: "Alphabet Inc.", enabled: true },
  { key: "AMZN", label: "Amazon.com Inc.", enabled: false },
  { key: "TSLA", label: "Tesla Inc.", enabled: true },
  { key: "META", label: "Meta Platforms Inc.", enabled: false },
  { key: "NVDA", label: "NVIDIA Corporation", enabled: true },
  { key: "NFLX", label: "Netflix Inc.", enabled: false },
  { key: "JPM", label: "JPMorgan Chase & Co.", enabled: true },
  { key: "JNJ", label: "Johnson & Johnson", enabled: false },
  { key: "V", label: "Visa Inc.", enabled: true },
  { key: "PG", label: "Procter & Gamble Co.", enabled: false },
  { key: "UNH", label: "UnitedHealth Group Inc.", enabled: true },
  { key: "HD", label: "The Home Depot Inc.", enabled: false },
  { key: "MA", label: "Mastercard Inc.", enabled: true },
  { key: "DIS", label: "The Walt Disney Company", enabled: true },
  { key: "ADBE", label: "Adobe Inc.", enabled: false },
  { key: "CRM", label: "Salesforce Inc.", enabled: true },
  { key: "AMD", label: "Advanced Micro Devices Inc.", enabled: true },
  { key: "CSCO", label: "Cisco Systems Inc.", enabled: false },
  { key: "KO", label: "The Coca-Cola Company", enabled: false },
  { key: "WMT", label: "Walmart Inc.", enabled: true },
  // Additional symbols from your subscriptions
  { key: "BRK.B", label: "Berkshire Hathaway Inc.", enabled: true },
  { key: "TSM", label: "Taiwan Semiconductor", enabled: true },
  { key: "AVGO", label: "Broadcom Inc.", enabled: true },
  { key: "LLY", label: "Eli Lilly and Company", enabled: true },
  { key: "XOM", label: "Exxon Mobil Corporation", enabled: false },
  { key: "ORCL", label: "Oracle Corporation", enabled: true },
  { key: "COST", label: "Costco Wholesale Corporation", enabled: false },
  { key: "BAC", label: "Bank of America Corporation", enabled: true },
  { key: "NVO", label: "Novo Nordisk A/S", enabled: false },
  { key: "ABBV", label: "AbbVie Inc.", enabled: true },
  { key: "CVX", label: "Chevron Corporation", enabled: false },
  { key: "SAP", label: "SAP SE", enabled: false },
  { key: "TMUS", label: "T-Mobile US Inc.", enabled: true },
  { key: "ASML", label: "ASML Holding N.V.", enabled: true },
  { key: "MRK", label: "Merck & Co. Inc.", enabled: false },
  { key: "WFC", label: "Wells Fargo & Company", enabled: true },
  { key: "ACN", label: "Accenture plc", enabled: false },
  { key: "TM", label: "Toyota Motor Corporation", enabled: false },
  { key: "BX", label: "Blackstone Inc.", enabled: true },
  { key: "PEP", label: "PepsiCo Inc.", enabled: false },
  { key: "LIN", label: "Linde plc", enabled: true },
  { key: "MS", label: "Morgan Stanley", enabled: true },
  { key: "NOW", label: "ServiceNow Inc.", enabled: false },
  { key: "MCD", label: "McDonald's Corporation", enabled: false },
  { key: "NVS", label: "Novartis AG", enabled: false },
  { key: "PM", label: "Philip Morris International", enabled: false },
  { key: "AXP", label: "American Express Company", enabled: true },
];

// Updated CRYPTO_OPTIONS to only include what's available
export const CRYPTO_OPTIONS = [
  { key: "BINANCE:BTCUSDT", label: "Bitcoin (BTCUSDT)", enabled: true },
  { key: "ETH", label: "Ethereum", enabled: true },
  // Note: Only these 2 crypto symbols are available in your subscriptions.json
  // You can add more by updating your subscriptions.json file
];

export const THEMES = [
  {
    label: "Scrollr",
    value: "scrollr",
    colors: ["#f5f9fc", "#27aae2", "#fdd553"],
  },
  { label: "Light", value: "light", colors: ["#ffffff", "#833ef6", "#ff369a"] },
  { label: "Dark", value: "dark", colors: ["#2a303c", "#793ef9", "#ff0080"] },
  {
    label: "Cupcake",
    value: "cupcake",
    colors: ["#faf7f5", "#65c3c8", "#ef9fbc"],
  },
  {
    label: "Bumblebee",
    value: "bumblebee",
    colors: ["#ffffff", "#e0a82e", "#f9d72f"],
  },
  {
    label: "Emerald",
    value: "emerald",
    colors: ["#ffffff", "#66cc8a", "#377cfb"],
  },
  {
    label: "Corporate",
    value: "corporate",
    colors: ["#ffffff", "#4b6bfb", "#7b92b2"],
  },
  {
    label: "Synthwave",
    value: "synthwave",
    colors: ["#2b2164", "#f471b5", "#1bcdd4"],
  },
  { label: "Retro", value: "retro", colors: ["#e4d8b4", "#ff6b6b", "#fdca40"] },
  {
    label: "Cyberpunk",
    value: "cyberpunk",
    colors: ["#ffee00", "#ff7598", "#75d1f0"],
  },
  {
    label: "Valentine",
    value: "valentine",
    colors: ["#fae0e6", "#e96d7b", "#a991f7"],
  },
  {
    label: "Halloween",
    value: "halloween",
    colors: ["#212121", "#f28c18", "#6d3a9c"],
  },
  {
    label: "Garden",
    value: "garden",
    colors: ["#e8e8e8", "#5c7f67", "#ecf4e7"],
  },
  {
    label: "Forest",
    value: "forest",
    colors: ["#171212", "#1eb854", "#d99330"],
  },
  { label: "Aqua", value: "aqua", colors: ["#345da7", "#00cfbd", "#ffd200"] },
  { label: "Lofi", value: "lofi", colors: ["#ffffff", "#1a1a1a", "#808080"] },
  {
    label: "Pastel",
    value: "pastel",
    colors: ["#ffffff", "#d1c1d7", "#fadae1"],
  },
  {
    label: "Fantasy",
    value: "fantasy",
    colors: ["#ffffff", "#7e2495", "#0079d3"],
  },
  {
    label: "Wireframe",
    value: "wireframe",
    colors: ["#ffffff", "#b8b8b8", "#ebebeb"],
  },
  { label: "Black", value: "black", colors: ["#000000", "#141414", "#cccccc"] },
  {
    label: "Luxury",
    value: "luxury",
    colors: ["#09090b", "#ffffff", "#dca54c"],
  },
  {
    label: "Dracula",
    value: "dracula",
    colors: ["#282a36", "#ff80bf", "#8aff80"],
  },
  { label: "CMYK", value: "cmyk", colors: ["#ffffff", "#45aeee", "#e8488a"] },
  {
    label: "Autumn",
    value: "autumn",
    colors: ["#f2f2f2", "#8c0327", "#d85251"],
  },
  {
    label: "Business",
    value: "business",
    colors: ["#1f1f1f", "#1c4e80", "#7c909a"],
  },
  { label: "Acid", value: "acid", colors: ["#fafafa", "#ff00ff", "#ffaa00"] },
  {
    label: "Lemonade",
    value: "lemonade",
    colors: ["#ffffff", "#519903", "#dcc80d"],
  },
  { label: "Night", value: "night", colors: ["#1e232a", "#38bdf8", "#7dd3fc"] },
  {
    label: "Coffee",
    value: "coffee",
    colors: ["#1f1d1a", "#db924b", "#6f4e37"],
  },
  {
    label: "Winter",
    value: "winter",
    colors: ["#ffffff", "#057aea", "#4664aa"],
  },
  { label: "Dim", value: "dim", colors: ["#2a2e37", "#9ca3af", "#a3a3a3"] },
  { label: "Nord", value: "nord", colors: ["#2e3440", "#88c0d0", "#d8dee9"] },
  {
    label: "Sunset",
    value: "sunset",
    colors: ["#1a202c", "#f56565", "#ed8936"],
  },
  {
    label: "Caramellatte",
    value: "caramellatte",
    colors: ["#f7f3f0", "#d2691e", "#8b4513"],
  },
  { label: "Abyss", value: "abyss", colors: ["#000000", "#4c1d95", "#7c3aed"] },
  { label: "Silk", value: "silk", colors: ["#f8f9fa", "#6c757d", "#495057"] },
];
